// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ------------------------- //
// dmd_framedetect_capcom_hd //
// ------------------------- //

#define dmd_framedetect_capcom_hd_wrap_target 6
#define dmd_framedetect_capcom_hd_wrap 11
#define dmd_framedetect_capcom_hd_pio_version 0

static const uint16_t dmd_framedetect_capcom_hd_program_instructions[] = {
    0xe03f, //  0: set    x, 31
    0x4025, //  1: in     x, 5
    0xe021, //  2: set    x, 1
    0x4021, //  3: in     x, 1
    0x2006, //  4: wait   0 gpio, 6
    0x2086, //  5: wait   1 gpio, 6
            //     .wrap_target
    0xa026, //  6: mov    x, isr
    0x2085, //  7: wait   1 gpio, 5
    0x2005, //  8: wait   0 gpio, 5
    0x0047, //  9: jmp    x--, 7
    0xc005, // 10: irq    nowait 5
    0x2086, // 11: wait   1 gpio, 6
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program dmd_framedetect_capcom_hd_program = {
    .instructions = dmd_framedetect_capcom_hd_program_instructions,
    .length = 12,
    .origin = -1,
    .pio_version = dmd_framedetect_capcom_hd_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x1
#endif
};

static inline pio_sm_config dmd_framedetect_capcom_hd_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + dmd_framedetect_capcom_hd_wrap_target, offset + dmd_framedetect_capcom_hd_wrap);
    return c;
}
#endif

