// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// -------------------- //
// dmd_reader_de_x16_v1 //
// -------------------- //

#define dmd_reader_de_x16_v1_wrap_target 0
#define dmd_reader_de_x16_v1_wrap 13
#define dmd_reader_de_x16_v1_pio_version 0

static const uint16_t dmd_reader_de_x16_v1_program_instructions[] = {
            //     .wrap_target
    0xe05f, //  0: set    y, 31
    0xc045, //  1: irq    clear 5
    0x20c5, //  2: wait   1 irq, 5
    0xe03f, //  3: set    x, 31
    0x2083, //  4: wait   1 gpio, 3
    0x4063, //  5: in     null, 3
    0x4003, //  6: in     pins, 3
    0x4062, //  7: in     null, 2
    0x2003, //  8: wait   0 gpio, 3
    0x0044, //  9: jmp    x--, 4
    0xe027, // 10: set    x, 7
    0x4060, // 11: in     null, 32
    0x004b, // 12: jmp    x--, 11
    0x0083, // 13: jmp    y--, 3
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program dmd_reader_de_x16_v1_program = {
    .instructions = dmd_reader_de_x16_v1_program_instructions,
    .length = 14,
    .origin = -1,
    .pio_version = dmd_reader_de_x16_v1_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x1
#endif
};

static inline pio_sm_config dmd_reader_de_x16_v1_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + dmd_reader_de_x16_v1_wrap_target, offset + dmd_reader_de_x16_v1_wrap);
    return c;
}
#endif

// ------------------------- //
// dmd_framedetect_de_x16_v1 //
// ------------------------- //

#define dmd_framedetect_de_x16_v1_wrap_target 0
#define dmd_framedetect_de_x16_v1_wrap 8
#define dmd_framedetect_de_x16_v1_pio_version 0

static const uint16_t dmd_framedetect_de_x16_v1_program_instructions[] = {
            //     .wrap_target
    0x2006, //  0: wait   0 gpio, 6
    0x2086, //  1: wait   1 gpio, 6
    0x00c4, //  2: jmp    pin, 4
    0x0000, //  3: jmp    0
    0xe030, //  4: set    x, 16
    0x2007, //  5: wait   0 gpio, 7
    0x2087, //  6: wait   1 gpio, 7
    0x0045, //  7: jmp    x--, 5
    0xc005, //  8: irq    nowait 5
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program dmd_framedetect_de_x16_v1_program = {
    .instructions = dmd_framedetect_de_x16_v1_program_instructions,
    .length = 9,
    .origin = -1,
    .pio_version = dmd_framedetect_de_x16_v1_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x1
#endif
};

static inline pio_sm_config dmd_framedetect_de_x16_v1_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + dmd_framedetect_de_x16_v1_wrap_target, offset + dmd_framedetect_de_x16_v1_wrap);
    return c;
}
#endif

