// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ---------------------- //
// dmd_framedetect_alving //
// ---------------------- //

#define dmd_framedetect_alving_wrap_target 2
#define dmd_framedetect_alving_wrap 10
#define dmd_framedetect_alving_pio_version 0

static const uint16_t dmd_framedetect_alving_program_instructions[] = {
    0x2006, //  0: wait   0 gpio, 6
    0x2086, //  1: wait   1 gpio, 6
            //     .wrap_target
    0xe03f, //  2: set    x, 31
    0xe042, //  3: set    y, 2
    0x2005, //  4: wait   0 gpio, 5
    0x2085, //  5: wait   1 gpio, 5
    0x0044, //  6: jmp    x--, 4
    0x2004, //  7: wait   0 gpio, 4
    0x2084, //  8: wait   1 gpio, 4
    0x0087, //  9: jmp    y--, 7
    0xc005, // 10: irq    nowait 5
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program dmd_framedetect_alving_program = {
    .instructions = dmd_framedetect_alving_program_instructions,
    .length = 11,
    .origin = -1,
    .pio_version = dmd_framedetect_alving_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x1
#endif
};

static inline pio_sm_config dmd_framedetect_alving_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + dmd_framedetect_alving_wrap_target, offset + dmd_framedetect_alving_wrap);
    return c;
}
#endif

