// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// --------------- //
// dmd_reader_2bpp //
// --------------- //

#define dmd_reader_2bpp_wrap_target 0
#define dmd_reader_2bpp_wrap 8
#define dmd_reader_2bpp_pio_version 0

static const uint16_t dmd_reader_2bpp_program_instructions[] = {
            //     .wrap_target
    0xa027, //  0: mov    x, osr
    0xa0c3, //  1: mov    isr, null
    0xc045, //  2: irq    clear 5
    0x20c5, //  3: wait   1 irq, 5
    0x2003, //  4: wait   0 gpio, 3
    0x4061, //  5: in     null, 1
    0x2083, //  6: wait   1 gpio, 3
    0x4001, //  7: in     pins, 1
    0x0044, //  8: jmp    x--, 4
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program dmd_reader_2bpp_program = {
    .instructions = dmd_reader_2bpp_program_instructions,
    .length = 9,
    .origin = -1,
    .pio_version = dmd_reader_2bpp_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x1
#endif
};

static inline pio_sm_config dmd_reader_2bpp_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + dmd_reader_2bpp_wrap_target, offset + dmd_reader_2bpp_wrap);
    return c;
}
#endif

