// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// --------------------- //
// dmd_framedetect_sleic //
// --------------------- //

#define dmd_framedetect_sleic_wrap_target 3
#define dmd_framedetect_sleic_wrap 8
#define dmd_framedetect_sleic_pio_version 0

static const uint16_t dmd_framedetect_sleic_program_instructions[] = {
    0xe023, //  0: set    x, 3
    0x4022, //  1: in     x, 2
    0x406b, //  2: in     null, 11
            //     .wrap_target
    0xa026, //  3: mov    x, isr
    0x2007, //  4: wait   0 gpio, 7
    0x00c3, //  5: jmp    pin, 3
    0x0045, //  6: jmp    x--, 5
    0x2086, //  7: wait   1 gpio, 6
    0xc005, //  8: irq    nowait 5
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program dmd_framedetect_sleic_program = {
    .instructions = dmd_framedetect_sleic_program_instructions,
    .length = 9,
    .origin = -1,
    .pio_version = dmd_framedetect_sleic_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x1
#endif
};

static inline pio_sm_config dmd_framedetect_sleic_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + dmd_framedetect_sleic_wrap_target, offset + dmd_framedetect_sleic_wrap);
    return c;
}
#endif

