// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// --------------------- //
// dmd_framedetect_spike //
// --------------------- //

#define dmd_framedetect_spike_wrap_target 3
#define dmd_framedetect_spike_wrap 12
#define dmd_framedetect_spike_pio_version 0

static const uint16_t dmd_framedetect_spike_program_instructions[] = {
    0xe023, //  0: set    x, 3
    0x4022, //  1: in     x, 2
    0x406d, //  2: in     null, 13
            //     .wrap_target
    0x2086, //  3: wait   1 gpio, 6
    0xa026, //  4: mov    x, isr
    0x0045, //  5: jmp    x--, 5
    0x00c8, //  6: jmp    pin, 8
    0x0003, //  7: jmp    3
    0xe03e, //  8: set    x, 30
    0x2085, //  9: wait   1 gpio, 5
    0x2005, // 10: wait   0 gpio, 5
    0x0049, // 11: jmp    x--, 9
    0xc005, // 12: irq    nowait 5
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program dmd_framedetect_spike_program = {
    .instructions = dmd_framedetect_spike_program_instructions,
    .length = 13,
    .origin = -1,
    .pio_version = dmd_framedetect_spike_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x1
#endif
};

static inline pio_sm_config dmd_framedetect_spike_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + dmd_framedetect_spike_wrap_target, offset + dmd_framedetect_spike_wrap);
    return c;
}
#endif

