// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ---------------- //
// dmd_count_signal //
// ---------------- //

#define dmd_count_signal_wrap_target 1
#define dmd_count_signal_wrap 3
#define dmd_count_signal_pio_version 0

static const uint16_t dmd_count_signal_program_instructions[] = {
    0xa023, //  0: mov    x, null
            //     .wrap_target
    0x2020, //  1: wait   0 pin, 0
    0x0043, //  2: jmp    x--, 3
    0x20a0, //  3: wait   1 pin, 0
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program dmd_count_signal_program = {
    .instructions = dmd_count_signal_program_instructions,
    .length = 4,
    .origin = -1,
    .pio_version = dmd_count_signal_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config dmd_count_signal_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + dmd_count_signal_wrap_target, offset + dmd_count_signal_wrap);
    return c;
}
#endif

