// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ----------------------- //
// dmd_framedetect_homepin //
// ----------------------- //

#define dmd_framedetect_homepin_wrap_target 0
#define dmd_framedetect_homepin_wrap 3
#define dmd_framedetect_homepin_pio_version 0

static const uint16_t dmd_framedetect_homepin_program_instructions[] = {
            //     .wrap_target
    0x2006, //  0: wait   0 gpio, 6
    0x2086, //  1: wait   1 gpio, 6
    0x2006, //  2: wait   0 gpio, 6
    0xc005, //  3: irq    nowait 5
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program dmd_framedetect_homepin_program = {
    .instructions = dmd_framedetect_homepin_program_instructions,
    .length = 4,
    .origin = -1,
    .pio_version = dmd_framedetect_homepin_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x1
#endif
};

static inline pio_sm_config dmd_framedetect_homepin_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + dmd_framedetect_homepin_wrap_target, offset + dmd_framedetect_homepin_wrap);
    return c;
}
#endif

