// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ---------------------- //
// dmd_framedetect_desega //
// ---------------------- //

#define dmd_framedetect_desega_wrap_target 0
#define dmd_framedetect_desega_wrap 8
#define dmd_framedetect_desega_pio_version 0

static const uint16_t dmd_framedetect_desega_program_instructions[] = {
            //     .wrap_target
    0x2007, //  0: wait   0 gpio, 7
    0xe034, //  1: set    x, 20
    0xbf42, //  2: nop                           [31]
    0xbf42, //  3: nop                           [31]
    0x0042, //  4: jmp    x--, 2
    0x00c0, //  5: jmp    pin, 0
    0xc005, //  6: irq    nowait 5
    0x2087, //  7: wait   1 gpio, 7
    0x0000, //  8: jmp    0
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program dmd_framedetect_desega_program = {
    .instructions = dmd_framedetect_desega_program_instructions,
    .length = 9,
    .origin = -1,
    .pio_version = dmd_framedetect_desega_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x1
#endif
};

static inline pio_sm_config dmd_framedetect_desega_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + dmd_framedetect_desega_wrap_target, offset + dmd_framedetect_desega_wrap);
    return c;
}
#endif

