// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// -------------------- //
// dmd_reader_de_x16_v2 //
// -------------------- //

#define dmd_reader_de_x16_v2_wrap_target 2
#define dmd_reader_de_x16_v2_wrap 21
#define dmd_reader_de_x16_v2_pio_version 0

static const uint16_t dmd_reader_de_x16_v2_program_instructions[] = {
    0x20c5, //  0: wait   1 irq, 5
    0xa0c3, //  1: mov    isr, null
            //     .wrap_target
    0xe03f, //  2: set    x, 31
    0x2083, //  3: wait   1 gpio, 3
    0x4063, //  4: in     null, 3
    0x4003, //  5: in     pins, 3
    0x4062, //  6: in     null, 2
    0x2003, //  7: wait   0 gpio, 3
    0x0043, //  8: jmp    x--, 3
    0x006b, //  9: jmp    !y, 11
    0x0082, // 10: jmp    y--, 2
    0xa027, // 11: mov    x, osr
    0x00d5, // 12: jmp    pin, 21
    0x004c, // 13: jmp    x--, 12
    0xe025, // 14: set    x, 5
    0xe05f, // 15: set    y, 31
    0x4024, // 16: in     x, 4
    0x4024, // 17: in     x, 4
    0x0090, // 18: jmp    y--, 16
    0xa043, // 19: mov    y, null
    0x0002, // 20: jmp    2
    0xe041, // 21: set    y, 1
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program dmd_reader_de_x16_v2_program = {
    .instructions = dmd_reader_de_x16_v2_program_instructions,
    .length = 22,
    .origin = -1,
    .pio_version = dmd_reader_de_x16_v2_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x1
#endif
};

static inline pio_sm_config dmd_reader_de_x16_v2_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + dmd_reader_de_x16_v2_wrap_target, offset + dmd_reader_de_x16_v2_wrap);
    return c;
}
#endif

// ------------------------- //
// dmd_framedetect_de_x16_v2 //
// ------------------------- //

#define dmd_framedetect_de_x16_v2_wrap_target 0
#define dmd_framedetect_de_x16_v2_wrap 6
#define dmd_framedetect_de_x16_v2_pio_version 0

static const uint16_t dmd_framedetect_de_x16_v2_program_instructions[] = {
            //     .wrap_target
    0x2007, //  0: wait   0 gpio, 7
    0xa027, //  1: mov    x, osr
    0x0042, //  2: jmp    x--, 2
    0x00c6, //  3: jmp    pin, 6
    0x2087, //  4: wait   1 gpio, 7
    0x0000, //  5: jmp    0
    0xc005, //  6: irq    nowait 5
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program dmd_framedetect_de_x16_v2_program = {
    .instructions = dmd_framedetect_de_x16_v2_program_instructions,
    .length = 7,
    .origin = -1,
    .pio_version = dmd_framedetect_de_x16_v2_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x1
#endif
};

static inline pio_sm_config dmd_framedetect_de_x16_v2_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + dmd_framedetect_de_x16_v2_wrap_target, offset + dmd_framedetect_de_x16_v2_wrap);
    return c;
}
#endif

