// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ----------------- //
// dmd_reader_capcom //
// ----------------- //

#define dmd_reader_capcom_wrap_target 0
#define dmd_reader_capcom_wrap 14
#define dmd_reader_capcom_pio_version 0

static const uint16_t dmd_reader_capcom_program_instructions[] = {
            //     .wrap_target
    0xe05f, //  0: set    y, 31
    0xa0c3, //  1: mov    isr, null
    0xc045, //  2: irq    clear 5
    0x20c5, //  3: wait   1 irq, 5
    0xa027, //  4: mov    x, osr
    0x2003, //  5: wait   0 gpio, 3
    0x2083, //  6: wait   1 gpio, 3
    0x0045, //  7: jmp    x--, 5
    0xa027, //  8: mov    x, osr
    0x2003, //  9: wait   0 gpio, 3
    0x4063, // 10: in     null, 3
    0x2083, // 11: wait   1 gpio, 3
    0x4001, // 12: in     pins, 1
    0x0049, // 13: jmp    x--, 9
    0x0084, // 14: jmp    y--, 4
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program dmd_reader_capcom_program = {
    .instructions = dmd_reader_capcom_program_instructions,
    .length = 15,
    .origin = -1,
    .pio_version = dmd_reader_capcom_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x1
#endif
};

static inline pio_sm_config dmd_reader_capcom_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + dmd_reader_capcom_wrap_target, offset + dmd_reader_capcom_wrap);
    return c;
}
#endif

// ---------------------- //
// dmd_framedetect_capcom //
// ---------------------- //

#define dmd_framedetect_capcom_wrap_target 2
#define dmd_framedetect_capcom_wrap 7
#define dmd_framedetect_capcom_pio_version 0

static const uint16_t dmd_framedetect_capcom_program_instructions[] = {
    0x2006, //  0: wait   0 gpio, 6
    0x2086, //  1: wait   1 gpio, 6
            //     .wrap_target
    0xe03f, //  2: set    x, 31
    0x2085, //  3: wait   1 gpio, 5
    0x2005, //  4: wait   0 gpio, 5
    0x0043, //  5: jmp    x--, 3
    0xc005, //  6: irq    nowait 5
    0x2086, //  7: wait   1 gpio, 6
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program dmd_framedetect_capcom_program = {
    .instructions = dmd_framedetect_capcom_program_instructions,
    .length = 8,
    .origin = -1,
    .pio_version = dmd_framedetect_capcom_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x1
#endif
};

static inline pio_sm_config dmd_framedetect_capcom_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + dmd_framedetect_capcom_wrap_target, offset + dmd_framedetect_capcom_wrap);
    return c;
}
#endif

