// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// -------------- //
// dmd_reader_sam //
// -------------- //

#define dmd_reader_sam_wrap_target 7
#define dmd_reader_sam_wrap 15
#define dmd_reader_sam_pio_version 0

static const uint16_t dmd_reader_sam_program_instructions[] = {
    0xe03f, //  0: set    x, 31
    0x4025, //  1: in     x, 5
    0xe03f, //  2: set    x, 31
    0x4025, //  3: in     x, 5
    0xe02f, //  4: set    x, 15
    0x4024, //  5: in     x, 4
    0xa046, //  6: mov    y, isr
            //     .wrap_target
    0xa022, //  7: mov    x, y
    0xa0c3, //  8: mov    isr, null
    0xc045, //  9: irq    clear 5
    0x20c5, // 10: wait   1 irq, 5
    0x2004, // 11: wait   0 gpio, 4
    0x4063, // 12: in     null, 3
    0x2084, // 13: wait   1 gpio, 4
    0x4001, // 14: in     pins, 1
    0x004b, // 15: jmp    x--, 11
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program dmd_reader_sam_program = {
    .instructions = dmd_reader_sam_program_instructions,
    .length = 16,
    .origin = -1,
    .pio_version = dmd_reader_sam_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x1
#endif
};

static inline pio_sm_config dmd_reader_sam_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + dmd_reader_sam_wrap_target, offset + dmd_reader_sam_wrap);
    return c;
}
#endif

// ------------------- //
// dmd_framedetect_sam //
// ------------------- //

#define dmd_framedetect_sam_wrap_target 0
#define dmd_framedetect_sam_wrap 2
#define dmd_framedetect_sam_pio_version 0

static const uint16_t dmd_framedetect_sam_program_instructions[] = {
            //     .wrap_target
    0x2001, //  0: wait   0 gpio, 1
    0x2081, //  1: wait   1 gpio, 1
    0xc005, //  2: irq    nowait 5
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program dmd_framedetect_sam_program = {
    .instructions = dmd_framedetect_sam_program_instructions,
    .length = 3,
    .origin = -1,
    .pio_version = dmd_framedetect_sam_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x1
#endif
};

static inline pio_sm_config dmd_framedetect_sam_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + dmd_framedetect_sam_wrap_target, offset + dmd_framedetect_sam_wrap);
    return c;
}
#endif

