// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// -------------- //
// clocked_output //
// -------------- //

#define clocked_output_wrap_target 0
#define clocked_output_wrap 2
#define clocked_output_pio_version 0

static const uint16_t clocked_output_program_instructions[] = {
            //     .wrap_target
    0x6001, //  0: out    pins, 1
    0x20a0, //  1: wait   1 pin, 0
    0x2020, //  2: wait   0 pin, 0
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program clocked_output_program = {
    .instructions = clocked_output_program_instructions,
    .length = 3,
    .origin = -1,
    .pio_version = clocked_output_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config clocked_output_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + clocked_output_wrap_target, offset + clocked_output_wrap);
    return c;
}

static inline void clocked_output_program_init(PIO pio, uint sm, uint offset, uint pin_spi_base) {
    pio_sm_config c = clocked_output_program_get_default_config(offset);
    // Set the IN base pin to the provided `pin` parameter. This is the clock
    // pin
    sm_config_set_in_pins(&c, pin_spi_base+2);
    sm_config_set_out_pins(&c, pin_spi_base,1);
    // Set the pin direction at the PIO
    pio_sm_set_consecutive_pindirs(pio, sm, pin_spi_base+2, 1, false);
    pio_sm_set_consecutive_pindirs(pio, sm, pin_spi_base, 1, true);
    // Connect these GPIOs to this PIO block
    pio_gpio_init(pio, pin_spi_base+0);
    pio_gpio_init(pio, pin_spi_base+2);
    // Shifting to left matches the customary MSB-first ordering of SPI.
    sm_config_set_out_shift(
        &c,
        false,  // Shift-to-right = false
        true,  // Autopull enabled
        32     // Autopull threshold = 8
    );
    // We only send, so disable the RX FIFO to make the TX FIFO deeper.
    sm_config_set_fifo_join(&c, PIO_FIFO_JOIN_TX);
    sm_config_set_clkdiv(&c,1);
    // Load our configuration, and start the program from the beginning
    pio_sm_init(pio, sm, offset, &c);
    pio_sm_set_enabled(pio, sm, true);
}

#endif

