[platformio]
default_envs = rp2040

[env:rp2040]
platform = https://github.com/maxgerhardt/platform-raspberrypi/archive/5d4561a05e3b212660ac6fdd3fbfb328d1988aa1.tar.gz
framework = arduino
board = pico
board_build.core = earlephilhower
board_build.filesystem_size = 0.5m

[env:rp2350]
platform = https://github.com/maxgerhardt/platform-raspberrypi/archive/5d4561a05e3b212660ac6fdd3fbfb328d1988aa1.tar.gz
framework = arduino
board = rpipico2
board_build.core = earlephilhower
board_build.filesystem_size = 0.5m
build_flags =
    -DRP2350
